### ISSUE TITLE
Get request to Synapse

### ISSUE THREAD

**Issue by shehreyarahmedkohati** [TheHive-Project/Synapse#10]
Ubuntu 16.04 VM 
Hive,elasticsearch,cortex, synapse running.

I am trying to do a curl request to Synapse but I am unsuccessful

Using my personal hotmail account. With a TheHive folder.

Synapse.conf :
[api]
debug:False
host:0.0.0.0
port:5000
threaded:True

[TheHive]
url:http://192.168.132.129:9000
user:synapse
api_key: Zu14r4rpt7t****6wIrhuu3eGx8P

[EWS]
#ip or domain to EWS server
server: hotmail.com
#According to exchangelib doc:
#"username is usually in WINDOMAIN\username format
#some servers also accept usernames in PrimarySMTPAddress
#('myusername@example.com') format (Office365 requires it)
username:hotmail.com\attitude_mine4
password:*******
smtp_address:attitude_mine4@hotmail.com
folder_name:TheHive

The curl command with synapse.hotmail.com/ews2case returns could not resolve synapse.hotmail.com. I have also set the certificate. Please help

**Comment by ninSmith** [comment]
Try to use your email address as username:

```
username:attitude_mine4@hotmail.com
```

The ```WINDOMAIN\username``` format is only intended to corporate environment where an AD server is set up with Exchange.

**Comment by shehreyarahmedkohati** [comment]
Thanks @ninSmith this worked. I am getting a {Success:false} error.

Below is my synapse.conf file: 

[api]
debug:False
host: 0.0.0.0
port:5000
threaded:True

[TheHive]
url:http://192.168.132.129:9000
user:synapse
api_key:Zu14re2pt*****Iql6wIrhuu3eGx8P

[EWS]
#ip or domain to EWS server
server: outlook.live.com
#According to exchangelib doc:
#"username is usually in WINDOMAIN\username format
#some servers also accept usernames in PrimarySMTPAddress
#('myusername@example.com') format (Office365 requires it)
username:attitude_mine4@hotmail.com
password:********
smtp_address:attitude_mine4@hotmail.com
folder_name:TheHive
I am using the certificate named DigiCert Cloud service CA-1. I have 4 certificates named DigiCert so I tried all of them. The etc/environment is set with the certificate file. The error from logs say Certificate Validation failed. But I have uploaded the correct one in place here "/usr/local/share/ca-certificates/extra". Below is the last log from my latest curl request: 

2018-10-17 03:43:12,549 :: INFO :: workflows.Ews2Case.connectEws starts
2018-10-17 03:43:12,549 :: INFO :: common.common.getConf starts
2018-10-17 03:43:12,551 :: INFO :: objects.EwsConnector. getAccount starts
2018-10-17 03:43:31,804 :: ERROR :: Failed to get account
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f28e98a4860>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='outlook.office.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f28e98a4860>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 28, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 176, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 227, in __init__
    self.docs_auth_type = get_docs_authtype(docs_url=self.types_url)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 131, in get_docs_authtype
    r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, timeout=BaseProtocol.TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='outlook.office.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f28e98a4860>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2018-10-17 03:43:31,806 :: ERROR :: Failed to create case from email
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f28e98a4860>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='outlook.office.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f28e98a4860>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Synapse-master/workflows/Ews2Case.py", line 25, in connectEws
    ewsConnector = EwsConnector(cfg)
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 13, in __init__
    self.account = self.getAccount()
  File "/opt/Synapse-master/workflows/objects/EwsConnector.py", line 28, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 176, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 227, in __init__
    self.docs_auth_type = get_docs_authtype(docs_url=self.types_url)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 131, in get_docs_authtype
    r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, timeout=BaseProtocol.TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='outlook.live.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f28e98a4860>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

Please help me in finding my mistake

**Comment by ninSmith** [comment]
I am not able to reproduce your issue.
With ```live.outlook.com``` you do not need any certificate manipulation, so try again configuring certificate.

**Comment by shehreyarahmedkohati** [comment]
@ninSmith I am particularly getting the error SSL Certificate Validation Failed with outlook.live.com 
Regardless, I tried to do it without the certificate too. But still the error exists.

**Comment by ninSmith** [comment]
Do you use a proxy ?

**Comment by shehreyarahmedkohati** [comment]
No I dont use any proxy. I am using a Virtual Machine that's on NAT by the way

**Comment by shehreyarahmedkohati** [comment]
Can there be a python issue here. Because while installing dependencies from the requirements.tx file. I incurred errors especially with cryptography library. It required some pre requisites that I installed manually.

**Comment by ninSmith** [comment]
Can you show the content of ```/etc/environment``` ?

**Comment by shehreyarahmedkohati** [comment]
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
JAVA_HOME="/usr/lib/jvm/java-8-oracle"

**Comment by shehreyarahmedkohati** [comment]
I removed the path to certificate "/usr/local/share/ca-certificates/extra/certfile.cer" after you said

**Comment by shehreyarahmedkohati** [comment]
Can it be the case as stated in [https://github.com/TheHive-Project/Synapse/issues/1](url)

**Comment by ninSmith** [comment]
Are you using O365 ? I thought it was a free hotmail account

**Comment by shehreyarahmedkohati** [comment]
Yes I am using a free hotmail account. I thought it might relate to what I was doing.

**Comment by shehreyarahmedkohati** [comment]
@ninSmith It'll be great if you can upload a VM image for me somewhere with Synapse running.

**Comment by shehreyarahmedkohati** [comment]
Thanks, I'll wait. @ninSmith

**Comment by shehreyarahmedkohati** [comment]
@ninSmith I have successfully integrated synapse with Office365 server.
