### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by znb** [TheHive-Project/Synapse#14]
Ran into this while testing Synapse 1.1.0

OS: Ubuntu 16.04

`
2018-11-12 12:55:07,583 :: INFO :: objects.TempAttachment.getFileName starts
2018-11-12 12:55:07,583 :: ERROR :: Failed to create case from email
Traceback (most recent call last):
  File "/opt/Synapse/workflows/Ews2Case.py", line 85, in connectEws
    tempAttachment = TempAttachment(attachmentLvl1)
  File "/opt/Synapse/workflows/objects/TempAttachment.py", line 60, in __init__
    self.filename = self.getFilename()
  File "/opt/Synapse/workflows/objects/TempAttachment.py", line 83, in getFilename
    filename = slugify(filename)
  File "/usr/local/lib/python3.5/dist-packages/slugify.py", line 24, in slugify
    unicode(
NameError: name 'unicode' is not defined
`

The case is created but I believe the issue is with saving and attaching the attachment.

Let me know what other information you need.

M

**Comment by ninSmith** [comment]
Erf, I guess that's on me.   
Try the following:

 * Stop synapse
 * ```sudo pip3 uninstall slugify```
 * ```sudo pip3 install python-slugify```

And try to import a new email with an attachment (doesn't matter if it is the same attachment or not).

**Comment by znb** [comment]
@ninSmith 

Yup..this sorted it.

Thank you.

**Comment by ninSmith** [comment]
Good, I'll issue a hotfix tonight, thank you for reporting this :)
