### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by JorgeJuanMartin** [TheHive-Project/Synapse#16]
Hi,

I am having an issue with the certificate. aparently synapse does not trus the cert. Would it be possible to config synapse to not verify certificates?? 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Synapse/workflows/objects/EwsConnector.py", line 34, in getAccount
    auth_type=None)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 186, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 221, in __init__
    name=self.credentials.username)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 136, in get_service_authtype
    timeout=BaseProtocol.TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='sting.omniaccess.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
2018-11-22 12:25:56,187 :: ERROR :: Failed to create case from email
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

**Comment by JorgeJuanMartin** [comment]
Hi ninSmith 

how do you extract your certificate ? Do you have a proxy in your context ?

I do not have a proxy. I go to my outlook server via HTTPS --> browser configuration --> certificates 
I export the certificate in Base64. It creates a .cer file. 
I copy the cert into the route and edit CA_BUNDLE as indicated

Best regards

**Comment by ninSmith** [comment]
Have you tried with the full certification path ?
With firefox it's called "X.509 Certificate with chain (PEM)"

**Comment by JorgeJuanMartin** [comment]
there is no option to save the cert in a PEM format

And I realize that REQUEST_CA_BUNDLE is not picking up the current route

root@openvas:/opt/Synapse/conf# cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/extra/owacertificado.p7b



root@openvas:/opt/Synapse/conf# curl localhost:5000/ews2case
{"success":false}
root@openvas:/opt/Synapse/conf# sypaselog
sypaselog: command not found
root@openvas:/opt/Synapse/conf# synapselog
2018-11-28 14:45:57,606 :: ERROR :: Failed to get account
Traceback (most recent call last):
  File "/opt/Synapse/workflows/objects/EwsConnector.py", line 29, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 186, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 239, in __init__
    self.docs_auth_type = get_docs_authtype(docs_url=self.types_url)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 120, in get_docs_authtype
    r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, timeout=BaseProtocol.TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 228, in cert_verify
    "invalid path: {}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /usr/local/share/ca-certificates/extra/owacert.cer
2018-11-28 14:45:57,610 :: ERROR :: Failed to create case from email
Traceback (most recent call last):
  File "/opt/Synapse/workflows/Ews2Case.py", line 25, in connectEws
    ewsConnector = EwsConnector(cfg)
  File "/opt/Synapse/workflows/objects/EwsConnector.py", line 13, in __init__
    self.account = self.getAccount()
  File "/opt/Synapse/workflows/objects/EwsConnector.py", line 29, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 186, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 239, in __init__
    self.docs_auth_type = get_docs_authtype(docs_url=self.types_url)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 120, in get_docs_authtype
    r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, timeout=BaseProtocol.TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 228, in cert_verify
    "invalid path: {}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /usr/local/share/ca-certificates/extra/owacert.cer

**Comment by ninSmith** [comment]
try to:

 * convert your cert to PEM: https://serverfault.com/questions/417140/convert-from-p7b-to-pem-via-openssl
 * edit REQUEST_CA_BUNDLE
 * restart Synapse
 * try ews2case again

**Comment by JorgeJuanMartin** [comment]
I converted the cert, copy in the route:
/usr/local/share/ca-certificates/extra/
But looks like synapse is still trying to use the old one (.cer)
I check that REQUEST_CA_BUNDLE is ok:
/usr/local/share/ca-certificates/extra/owacertificado.p7b
and restarted syanpse.

But at the time to do the curl it is like syanpse is using the old value for  REQUEST_CA_BUNDLE

Thanks in advance for your help!!

2018-11-28 16:11:50,496 :: ERROR :: Failed to get account
Traceback (most recent call last):
  File "/opt/Synapse/workflows/objects/EwsConnector.py", line 29, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 186, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 239, in __init__
    self.docs_auth_type = get_docs_authtype(docs_url=self.types_url)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 120, in get_docs_authtype
    r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, timeout=BaseProtocol.TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 228, in cert_verify
    "invalid path: {}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /usr/local/share/ca-certificates/extra/owacert.cer
2018-11-28 16:11:50,498 :: ERROR :: Failed to create case from email
Traceback (most recent call last):
  File "/opt/Synapse/workflows/Ews2Case.py", line 25, in connectEws
    ewsConnector = EwsConnector(cfg)
  File "/opt/Synapse/workflows/objects/EwsConnector.py", line 13, in __init__
    self.account = self.getAccount()
  File "/opt/Synapse/workflows/objects/EwsConnector.py", line 29, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 186, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 239, in __init__
    self.docs_auth_type = get_docs_authtype(docs_url=self.types_url)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 120, in get_docs_authtype
    r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, timeout=BaseProtocol.TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 228, in cert_verify
    "invalid path: {}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /usr/local/share/ca-certificates/extra/owacert.cer
root@openvas:/opt/Synapse# echo $REQUESTS_CA_BUNDLE
/usr/local/share/ca-certificates/extra/owacertificado.p7b

**Comment by ninSmith** [comment]
Let's do another way, rename your new certificate into ```owacert.cer```, just to validate that the certificate is valid

**Comment by JorgeJuanMartin** [comment]
HTTPSConnectionPool(host='owa.omniaccess.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:3053)'

**Comment by ninSmith** [comment]
Is that the full log trace ?

**Comment by JorgeJuanMartin** [comment]
2018-11-28 16:34:40,229 :: INFO :: workflows.Ews2Case.connectEws starts
2018-11-28 16:34:40,231 :: INFO :: common.common.getConf starts
2018-11-28 16:34:40,233 :: INFO :: objects.EwsConnector. getAccount starts
2018-11-28 16:34:40,259 :: ERROR :: Failed to get account
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 336, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
ssl.SSLError: unknown error (_ssl.c:3053)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 338, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: unknown error (_ssl.c:3053)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='owa.omniaccess.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:3053)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Synapse/workflows/objects/EwsConnector.py", line 29, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 186, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 239, in __init__
    self.docs_auth_type = get_docs_authtype(docs_url=self.types_url)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 120, in get_docs_authtype
    r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, timeout=BaseProtocol.TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='owa.omniaccess.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:3053)'),))
2018-11-28 16:34:40,415 :: ERROR :: Failed to create case from email
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 336, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
ssl.SSLError: unknown error (_ssl.c:3053)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 338, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: unknown error (_ssl.c:3053)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='owa.omniaccess.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:3053)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Synapse/workflows/Ews2Case.py", line 25, in connectEws
    ewsConnector = EwsConnector(cfg)
  File "/opt/Synapse/workflows/objects/EwsConnector.py", line 13, in __init__
    self.account = self.getAccount()
  File "/opt/Synapse/workflows/objects/EwsConnector.py", line 29, in getAccount
    auth_type=NTLM)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 186, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 239, in __init__
    self.docs_auth_type = get_docs_authtype(docs_url=self.types_url)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 120, in get_docs_authtype
    r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, timeout=BaseProtocol.TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='owa.omniaccess.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:3053)'),))

**Comment by ninSmith** [comment]
Can you ping me on gitter https://gitter.im/TheHive-Project/TheHive ?
It'll be easier to troubleshoot

**Comment by ninSmith** [comment]
Solved, problem was a wrong certificate and the auth_type was set to NTLM instead of None
