### ISSUE TITLE
Curl {"success":false} -- ValueError: unknown use case after searching case by description

### ISSUE THREAD

**Issue by ghost** [TheHive-Project/Synapse#70]
Hello,

I am stuck at trying to initiate curl to create the case, I check the logs and it provides me with 

Traceback (most recent call last):
  File "/opt/Synapse/workflows/Ews2Case.py", line 38, in connectEws
    esCaseId = theHiveConnector.searchCaseByDescription(conversationId)
  File "/opt/Synapse/workflows/objects/TheHiveConnector.py", line 57, in searchCaseByDescription
    raise ValueError('unknown use case after searching case by description')
ValueError: unknown use case after searching case by description

Not sure where to go from here? Any help would be appreciated. I will also attach my screenshot of the log:

![image](https://user-images.githubusercontent.com/61601721/126555799-4213c861-2949-4019-ad84-27ed04086f33.png)

**Comment by ghost** [comment]
**Update**
I tried the curl cmd on a server rather than my workstation, it said Success:True but never created a case, I looked in the logs and didn't find much, I tried again and now it said false again and won't work again. So not sure what is going on...

**Comment by ghost** [comment]
I've gotten the curl command to say Success:True every time now, but it still returns the error line 38 and line 57 where it states raise ValueError ('unknown use case after searching case by description')

Any help or advice would be great. Thanks!

**Comment by forghani77** [comment]
I have this issue too.
in TheHiveConnector.py file , line 38 it queries TheHive to check if there is an existing case with the passed query or not.
`        response = self.theHiveApi.find_cases(query=query, range=range, sort=sort)
`
I added `print(len(response.json()))` and it returned number of all of my cases in TheHive.
so thehive4py is broken?
